
Vagrant.configure("2") do |config|

  # Enable Hostmanager
  config.hostmanager.enabled = true
  config.hostmanager.manage_host = true

  
  config.vm.define "jenkins" do |machine|
    machine.vm.box = "ubuntu/jammy64"
    machine.vm.network "private_network", ip: "192.168.56.200"
    machine.vm.hostname = "jenkins"
    machine.vm.provider "virtualbox" do |vb|
      vb.memory = "4048"
      vb.cpus = "2"
      vb.customize [ "modifyvm", :id, "--uartmode1", "disconnected" ]
    end
  end
end
