
Vagrant.configure("2") do |config|

  # Enable Hostmanager
  config.hostmanager.enabled = true
  config.hostmanager.manage_host = true

  config.vm.define "scriptbox" do |machine|
    machine.vm.box = "eurolinux-vagrant/centos-stream-9"
    machine.vm.network "private_network", ip: "192.168.56.41"
    machine.vm.hostname = "scriptbox"
    machine.vm.provider "virtualbox" do |vb|
      vb.memory = "2048"
      vb.cpus = "1"
    end
  end

  config.vm.define "web01" do |machine|
    machine.vm.box = "eurolinux-vagrant/centos-stream-9"
    machine.vm.network "private_network", ip: "192.168.56.42"
    machine.vm.hostname = "web01"
    machine.vm.provider "virtualbox" do |vb|
      vb.memory = "2048"
      vb.cpus = "1"
    end
  end

  config.vm.define "web02" do |machine|
    machine.vm.box = "eurolinux-vagrant/centos-stream-9"
    machine.vm.network "private_network", ip: "192.168.56.43"
    machine.vm.hostname = "web02"
    machine.vm.provider "virtualbox" do |vb|
      vb.memory = "2048"
      vb.cpus = "1"
    end
  end

  config.vm.define "web03" do |machine|
    machine.vm.box = "ubuntu/jammy64"
    machine.vm.network "private_network", ip: "192.168.56.44"
    machine.vm.hostname = "web03"
    machine.vm.provider "virtualbox" do |vb|
      vb.memory = "2048"
      vb.cpus = "1"
      vb.customize [ "modifyvm", :id, "--uartmode1", "disconnected" ]
    end
  end
end
